### ISSUE TITLE
"validate.kyverno.svc-ignore" denied the request: resource Job/deploykf-auth/deploykf-auth-generate-secrets

### ISSUE THREAD

**Issue by namirinz** [deployKF/deployKF#180]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT security related. (Please [disclose responsibly](https://github.com/deployKF/deployKF/security))
- [X] This issue is NOT specific to the CLI. (Please open a [CLI issue](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.5

### Kubernetes Distribution

k8s

### Kubernetes Version

```shell
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.14+k0s
```

### Description

I try to sync `dkf-core--deploykf-auth` but got this error:

> admission webhook "validate.kyverno.svc-ignore" denied the request: resource Job/deploykf-auth/deploykf-auth-generate-secrets was blocked due to the following policies require-requests-limits: autogen-validate-resources: 'validation error: CPU and memory resource requests and limits are required. rule autogen-validate-resources failed at path /spec/template/spec/containers/1/resources/limits/' restrict-image-registries: autogen-validate-allow-registries: 'validation failure: failed to check deny preconditions: failed to substitute variables in condition value: failed to resolve allowedregistries.data.registries | parse_yaml(@) at path : JMESPath query failed: Invalid type for: <nil>, expected: []jmespath.JpType{"string"}'

FYI: I already have an existing kyverno in my cluster but the doc for using existing kyverno is not available so I also deploy kyverno from deployKF itself.

**Comment by thesuperzapper** [comment]
@namirinz please know that you can NOT run two versions of Kyverno on the same cluster! It will almost certainly break your cluster because both will be trying to fight each other for control of almost everything.

Right now, you are correct that we don't document how use an existing Kyverno install, this is because deployKF 0.1.5 depends on using [__exactly__ version `1.10.0` of Kyverno](https://www.deploykf.org/releases/version-matrix/#kyverno), and users are unlikely to have exactly that version.

We hope to update the embedded version of Kyverno in the next release, and provide instructions for using an existing Kyverno, but every version past 1.10.0 has had some critical flaw preventing us from using it.

We will make 1.12.X work, but it needs testing, there has been a significant change with the ClusterPolicy that replicates secrets. If the policy is created __before__ the source Secret it wont replicate until the undocumented `BACKGROUND_SCAN_INTERVAL` (https://github.com/kyverno/kyverno/issues/9560) has elapsed. But I think I have a workaround (where you set the `match` to the Secret itself rather than the target Namespace).

**Comment by namirinz** [comment]
@thesuperzapper So the only way to use deployKF for now is to remove the existing kyverno in the cluster and use embedded kyverno from deployKF? (or could I disable Kyverno ?)

**Comment by thesuperzapper** [comment]
I am going to close this because it's not technically an issue with deployKF.

But we are actively working on getting a newer version of Kyverno in deployKF 0.1.6 (see the changelog for more info about it).
