### ISSUE TITLE
Cannot delete app-of-apps

### ISSUE THREAD

**Issue by theNewFlesh** [deployKF/deployKF#24]
### Checks

- [X] I have searched the [existing issues](https://github.com/deployKF/deployKF).
- [X] This issue is NOT specific to the CLI. (If so, please open an issue on the [CLI repo](https://github.com/deployKF/cli/issues))

### deployKF Version

0.1.1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-21T14:01:24Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.27) exceeds the supported minor version skew of +/-1
```

### Description

I cannot delete the app of apps. Its gets stuck on ConfigMaps with finalizers. ArgoCD will not let me edit them to `finalizers: []` so they can go away.

Look like you need a script or additional K8s preflight logic to run that allows you to reliably delete the entire app.

Currently stuck in limbo.

**Comment by thesuperzapper** [comment]
@theNewFlesh in my testing deletion works, can you clarify which piece you attempted to delete?

Specifically, which ArgoCD application you tried to delete?

**Comment by thesuperzapper** [comment]
Posting here for reference as @theNewFlesh and I discussed this on the slack.

This issue was related to Kyverno not removing its `ValidatingWebhookConfigurations` and `MutatingWebhookConfigurations` when it was deleted. Because they are configured with a `failurePolicy` of `Fail` (that is, if the service they point to is not up, deny the request), requests on the cluster get deadlocked until you manually remove those cluster resources.

This was a bug in Kyverno's helm chart, discussed here https://github.com/kyverno/kyverno/issues/7576.

We will fix it in deployKF by enabling the pre-delete "cleanup job" that their chart includes.
